spring:
  application:
    name: api-health-monitor
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/api_health_monitor?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.yoona.apihealthmonitor: INFO
